bootstrap.servers=172.16.11.1:9092,172.16.11.252:9092,172.16.11.89:9092
group.id=realisation_wwb
auto.offset.reset=latest
kafka2hdfs.topics=realisation
kafka2hdfs.kafka.consume.from=1612345505000
source.raw.data.parallelism=1
checkpoint.data.uri=hdfs://recessw-hdp3-manager001:8020/flink_realtime_warehouse/checkpoint
kafka2hdfs.uri=hdfs://recessw-hdp3-manager001:8020/flink_realtime_warehouse/kafka2hdfs
kafka2hdfs.rollover.interval=180000
kafka2hdfs.inactivity.interval=300000
kafka2hdfs.max.part.size=1